apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: map-app-git-pipelinerun
  namespace: idankatz-dev
spec:
  pipelineRef:
    name: map-app-git-pipeline

  params:
    - name: git-url
      value: https://github.com/idankatzle/konflux-apps-config.git
    - name: git-revision
      value: master

  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

