apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: map-app-git-pipeline
  namespace: idankatz-dev
spec:
  workspaces:
    - name: shared-workspace

  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: master
    - name: image
      type: string
      default: image-registry.openshift-image-registry.svc:5000/idankatz-dev/map-app:latest

  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: subdirectory
          value: source
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-image
      runAfter:
        - clone-repo
      taskRef:
        name: build-kaniko-map-app
      params:
        - name: IMAGE
          value: $(params.image)
      workspaces:
        - name: source
          workspace: shared-workspace

