apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deploy-my-app
spec:
  params:
    - name: APP_PATH
      default: dev/my-web-app/base
      type: string
    - name: GIT_URL
      default: 'https://github.com/idankatzle/konflux-apps-config.git'
      type: string
  workspaces:
    - name: shared-data
  tasks:
    - name: git-clone
      params:
        - name: URL
          value: $(params.GIT_URL)
        - name: REVISION
          value: master
        - name: DELETE_EXISTING
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
    - name: apply-manifests
      runAfter:
        - git-clone
      params:
        - name: SCRIPT
          value: |
            cd $(workspaces.manifest_dir.path)/$(params.APP_PATH)
            oc apply -k .
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest_dir
          workspace: shared-data
