apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deploy-my-app
spec:
  workspaces:
    - name: shared-data
  tasks:
    - name: git-clone
      params:
        - name: url
          value: https://github.com/idankatzle/konflux-apps-config.git
        - name: revision
          value: master
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
    - name: apply-manifests
      runAfter:
        - git-clone
      params:
        - name: SCRIPT
          value: |
            # Navigation to the exact path from your GitHub structure
            TARGET_DIR="$(workspaces.manifest-dir.path)/dev/my-web-app/base"
            
            if [ -d "$TARGET_DIR" ]; then
              cd "$TARGET_DIR"
              echo "Applying manifests from: $(pwd)"
              oc apply -k .
            else
              echo "Directory not found! Current content of workspace:"
              ls -R $(workspaces.manifest-dir.path)
              exit 1
            fi
      taskRef:
        kind: Task
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: shared-data
