apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  params:
    - name: repo_url
      type: string
    - name: image
      type: string
    - name: CONTEXT
      type: string
      default: "src"
    - name: DOCKERFILE
      type: string
      default: "Dockerfile"
  workspaces:
    - name: source
  tasks:
    - name: clone
      taskRef:
        name: git-clone-local
      params:
        - name: repo_url
          value: $(params.repo_url)
      workspaces:
        - name: source
          workspace: source

    - name: build
      runAfter: [clone]
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: $(params.image)
        - name: CONTEXT
          value: $(params.CONTEXT)
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
      taskSpec:
        params:
          - name: IMAGE
          - name: CONTEXT
          - name: DOCKERFILE
        workspaces:
          - name: source
        steps:
          - name: build-and-push
            image: gcr.io/kaniko-project/executor:latest
            command: ["/kaniko/executor"]
            args:
              - "--dockerfile=$(workspaces.source.path)/$(params.CONTEXT)/$(params.DOCKERFILE)"
              - "--context=$(workspaces.source.path)/$(params.CONTEXT)"
              - "--destination=$(params.IMAGE)"
              - "--skip-tls-verify"
            volumeMounts:
              - name: kaniko-secret
                mountPath: /kaniko/.docker/
        volumes:
          - name: kaniko-secret
            secret:
              secretName: kaniko-docker-cfg
              items:
                - key: config.json
                  path: config.json

    # --- השלב החדש שהוספנו ---
    - name: deploy
      runAfter: [build] # ירוץ רק אם ה-build הצליח
      taskSpec:
        steps:
          - name: rollout
            image: quay.io/openshift/origin-cli:latest
            script: |
              #!/usr/bin/env bash
              oc rollout restart deployment/my-web -n idankatz-dev
              oc rollout status deployment/my-web -n idankatz-dev
