apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: idan-first-pipeline
spec:
  workspaces:
    - name: source

  tasks:
    - name: clone-code
      taskRef:
        name: git-clone-local
      params:
        - name: repo_url
          value: https://github.com/idankatzle/konflux-apps-config.git
        - name: revision
          value: master
      workspaces:
        - name: source
          workspace: source

    - name: list-files
      runAfter:
        - clone-code
      taskRef:
        name: hello-task
      workspaces:
        - name: task-workspace
          workspace: source

    - name: deploy-to-cluster
      runAfter:
        - list-files
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc apply -k $(workspaces.source.path)/dev/my-web-app/base
      workspaces:
        - name: source
          workspace: source

