apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-web
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
