apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  creationTimestamp: '2026-01-22T08:31:28Z'
  generation: 4
  managedFields:
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:finally': {}
          'f:params': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2026-01-22T08:35:30Z'
  name: migration-test
  namespace: idankatz-dev
  resourceVersion: '7146572006'
  uid: 57523222-41dd-47a8-b4b5-78dbde3bcbed
spec:
  finally:
    - name: openshift-client
      params:
        - name: SCRIPT
          value: |-
            cd $(workspaces.manifest_dir.path)/dev/konflux-1/base
            oc apply -k .
        - name: VERSION
          value: latest
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: openshift-client
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: manifest_dir
          workspace: shared-data
  tasks:
    - name: git-clone
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: ''
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: 'true'
        - name: URL
          value: 'https://github.com/idankatzle/konflux-apps-config.git'
        - name: REVISION
          value: master
        - name: REFSPEC
          value: ''
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ''
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: shared-data
  workspaces:
    - name: shared-data

