apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: idan-first-run-
spec:
  pipelineRef:
    name: idan-first-pipeline
  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: pipeline-pvc # השם שראינו ב-Bound סטטוס בתמונה שלך
